/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.woggioni.jpms.loader.example.bundle2;

import com.fasterxml.jackson.databind.ObjectMapper;
import net.woggioni.hello.jpms.a.A;
import net.woggioni.hello.jpms.a.P2d;

import java.lang.module.ModuleDescriptor;
import java.net.URL;
import java.util.Optional;


public class Bundle implements Runnable {

    @Override
    public void run() {
        P2d p1 = new P2d(1,2);
        P2d p2 = new P2d(3,4);
        System.out.println(A.distance(p1, p2));
        Module m = getClass().getModule();
        URL url = getClass().getClassLoader().getResource(ObjectMapper.class.getName().replace(".", "/") + ".class");
        System.out.printf("Module '%s' sees ObjectMapper from '%s'\n", m.getName(),  url);
        System.out.println(p1.toString());
    }
}
