/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.woggioni.hello.jpms;

import net.woggioni.hello.jpms.a.A;
import net.woggioni.hello.jpms.a.P2d;

public class Library {
    public static void main(String[] args) {
        P2d p1 = new P2d(1,2);
        P2d p2 = new P2d(3,4);
        System.out.println(A.distance(p1, p2));
        System.out.printf("Java version: %s\n", System.getProperty("java.version"));
    }
}
