/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.woggioni.hello.jpms;

import net.woggioni.jpms.loader.example.bundle2.Bundle;
import org.junit.jupiter.api.Test;

class LibraryTest {
    @Test
    void testSomeLibraryMethod() {
        Bundle classUnderTest = new Bundle();
    }
}
